items=crossbow
model=item/enchanted_crossbow_thin_extra
model.crossbow=item/enchanted_crossbow_thin_extra
model.crossbow_arrow=item/enchanted_crossbow_arrow_thin_extra
model.crossbow_firework=item/enchanted_crossbow_firework_thin_extra
model.crossbow_pulling_0=item/enchanted_crossbow_pulling_0_thin_extra
model.crossbow_pulling_1=item/enchanted_crossbow_pulling_1_thin_extra
model.crossbow_pulling_2=item/enchanted_crossbow_pulling_2_thin_extra
enchantmentLevels=1-255
