items = bow
model = item/enchanted_bow_thin_extra
model.bow_pulling_0 = item/enchanted_bow_pulling_0_thin_extra
model.bow_pulling_1 = item/enchanted_bow_pulling_1_thin_extra
model.bow_pulling_2 = item/enchanted_bow_pulling_2_thin_extra
enchantmentLevels = 1-255
